# Rename this file to languages.toml to enable multilingual support
[ko]
    languageName      = "한국어"
    languageCode      = "ko-kr"
    languagedirection = "ltr"
    title             = "JU HEON's Blog" # 여기에 블로그 제목을 적으세요
    weight            = 1